"""Add video support to posts

Revision ID: 2c33a6c375df
Revises: fa263f1f52ef
Create Date: 2024-09-11 10:44:13.355520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c33a6c375df'
down_revision = 'fa263f1f52ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('video_file', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'video_file')
    # ### end Alembic commands ###
