"""Add audio_file to Post model

Revision ID: fa263f1f52ef
Revises: 6718eaf6179f
Create Date: 2024-09-05 21:49:09.663179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa263f1f52ef'
down_revision = '6718eaf6179f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('audio_file', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'audio_file')
    # ### end Alembic commands ###
